export enum ScreenNames {
  //Public Screen
  LOGIN = 'LOGIN',
  REGISTER = 'REGISTER',
  HOME = 'HOME',
  TRENDING = 'TRENDING',
  SEARCH = 'SEARCH',
  MAIN_BOTTOM_TAB_NAVIGATOR = 'MAIN_BOTTOM_TAB_NAVIGATOR',
  MY_SELF = 'MY_SELF',
  MANGA = 'MANGA',
  CHAPTER = 'CHAPTER',
  GENRE = 'GENRE',
  STORYFILTER = 'STORYFILTER',
}
